_target_: src.models.bncde_module.BNCDEModule

covariate_size: ???
treatment_size: ???
outcome_size: ???
mc_samples: 1
hidden_size: 8
sd_diffusion: 0.001
drift_layers: [16, 64, 64, 64, 16]
intensity_weighting: false
prediction_window: 10
interpolation_method: linear
learning_rate: 0.0001
method: euler
coverage_metric_confidence: 0.95
