_target_: ??? 

net:
  _target_: src.models.components.cfode.CFODE
  covariate_size: ???
  treatment_size: ???
  outcome_size: ???
  hidden_size: 32
  num_layers: 1
  theta: 0.05
  mu: 0.0
  sigma: 0.1
  alpha: 0.0000025

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0005
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

visualize: false

# compile model for faster training with pytorch 2.0
compile: false
