_target_: ??? 

net:
  _target_: src.models.components.crn.CRN
  covariate_size: ???
  treatment_size: ???
  outcome_size: ???
  hidden_size: 64
  num_layers: 1
  p_dropout: 0.2

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

visualize: false
# compile model for faster training with pytorch 2.0
compile: false
