#!/bin/bash

log_dir=/home/tschw/Documents/Neuroengineering/causal_dynamics/uncertainty-aware-treatment-selection/logs

# Effect of the mse weight
HYDRA_FULL_ERROR=1 python src/treat.py experiment=crn_treat logger=wandb +logger.wandb.name=crn_run_cardiovascular_alpha_1 data=cardiovascular_dynamics ++model.visualize=false ++model._target_=src.models.sampled_uncertainty_module.SampledUncertaintyModule ++trainer.max_epochs=40 ++data.train_dataset.alpha=1.0 ++data.val_dataset.alpha=1.0 ++data.test_dataset.alpha=1.0
HYDRA_FULL_ERROR=1 python src/treat.py experiment=crn_treat logger=wandb +logger.wandb.name=crn_run_cardiovascular_alpha_2 data=cardiovascular_dynamics ++model.visualize=false ++model._target_=src.models.sampled_uncertainty_module.SampledUncertaintyModule ++trainer.max_epochs=40 ++data.train_dataset.alpha=2.0 ++data.val_dataset.alpha=2.0 ++data.test_dataset.alpha=2.0
HYDRA_FULL_ERROR=1 python src/treat.py experiment=crn_treat logger=wandb +logger.wandb.name=crn_run_cardiovascular_alpha_3 data=cardiovascular_dynamics ++model.visualize=false ++model._target_=src.models.sampled_uncertainty_module.SampledUncertaintyModule ++trainer.max_epochs=40 ++data.train_dataset.alpha=3.0 ++data.val_dataset.alpha=3.0 ++data.test_dataset.alpha=3.0
HYDRA_FULL_ERROR=1 python src/treat.py experiment=crn_treat logger=wandb +logger.wandb.name=crn_run_cardiovascular_alpha_4 data=cardiovascular_dynamics ++model.visualize=false ++model._target_=src.models.sampled_uncertainty_module.SampledUncertaintyModule ++trainer.max_epochs=40 ++data.train_dataset.alpha=4.0 ++data.val_dataset.alpha=4.0 ++data.test_dataset.alpha=4.0
HYDRA_FULL_ERROR=1 python src/treat.py experiment=crn_treat logger=wandb +logger.wandb.name=crn_run_cardiovascular_alpha_5 data=cardiovascular_dynamics ++model.visualize=false ++model._target_=src.models.sampled_uncertainty_module.SampledUncertaintyModule ++trainer.max_epochs=40 ++data.train_dataset.alpha=5.0 ++data.val_dataset.alpha=5.0 ++data.test_dataset.alpha=5.0
HYDRA_FULL_ERROR=1 python src/treat.py experiment=crn_treat logger=wandb +logger.wandb.name=crn_run_cardiovascular_alpha_6 data=cardiovascular_dynamics ++model.visualize=false ++model._target_=src.models.sampled_uncertainty_module.SampledUncertaintyModule ++trainer.max_epochs=40 ++data.train_dataset.alpha=6.0 ++data.val_dataset.alpha=6.0 ++data.test_dataset.alpha=6.0
HYDRA_FULL_ERROR=1 python src/treat.py experiment=crn_treat logger=wandb +logger.wandb.name=crn_run_cardiovascular_alpha_7 data=cardiovascular_dynamics ++model.visualize=false ++model._target_=src.models.sampled_uncertainty_module.SampledUncertaintyModule ++trainer.max_epochs=40 ++data.train_dataset.alpha=7.0 ++data.val_dataset.alpha=7.0 ++data.test_dataset.alpha=7.0
HYDRA_FULL_ERROR=1 python src/treat.py experiment=crn_treat logger=wandb +logger.wandb.name=crn_run_cardiovascular_alpha_8 data=cardiovascular_dynamics ++model.visualize=false ++model._target_=src.models.sampled_uncertainty_module.SampledUncertaintyModule ++trainer.max_epochs=40 ++data.train_dataset.alpha=8.0 ++data.val_dataset.alpha=8.0 ++data.test_dataset.alpha=8.0
